# Using Ubuntu 14.04 LTS as build environment
sudo: required
dist: trusty

language: python

python:
   - 2.7.11

# Install dependencies
install:
   - chmod 755 ./scripts/*
   - ./scripts/install_docker
   - ./scripts/install_docker_machine 
   - pip install -r requirements.txt

# Command to run test
script: python example.py 