# Using Ubuntu 14.04 LTS as build environment
sudo: required  
dist: trusty

language: python

python:
   - 2.7.11

services:
   - docker
   - docker-machine 

# Install dependencies
install:
   - pip install -r requirements.txt

# Command to run test
script: python example.py 